"""
====================================================================
AI / Synthetic Document Detection Module
Screening for AI-Generated & Synthetic Identity Documents

Evaluates multiple independent indicators:
1. Typography & Text Rendering Consistency (stroke width & baseline drift)
2. High-Frequency Diffusion Noise in Flat Regions
3. Hallucinatory / Gibberish Text Patterns
4. Portrait Photo & Card Integration Disparity
5. File Metadata & Generation Signatures

Disclaimer:
Preliminary probabilistic screening only. Does not claim 100% forensic certainty.
====================================================================
"""

import os
import re
import cv2
import numpy as np
from PIL import Image, ExifTags


def detect_ai_synthetic_indicators(image_path, ocr_data=None):
    """
    Analyzes an identity document for characteristic signatures of
    AI-generation (diffusion models, GANs, or synthetic generators).

    Returns:
        dict: {
            'status': 'PASSED' | 'WARNING' | 'FLAGGED',
            'indicator_count': int,
            'indicators': list of str,
            'risk_penalty': int (0, 10, or 30),
            'details': str,
            'metrics': dict,
            'disclaimer': str
        }
    """
    indicators = []
    metrics = {
        'baseline_drift_std': 0.0,
        'diffusion_noise_score': 0.0,
        'hallucinatory_token_count': 0,
        'photo_integration_anomaly': False,
        'metadata_ai_flag': False
    }

    if not os.path.exists(image_path):
        return {
            'status': 'PASSED',
            'indicator_count': 0,
            'indicators': [],
            'risk_penalty': 0,
            'details': 'File not found for synthetic screening.',
            'metrics': metrics,
            'disclaimer': 'AI/Synthetic Indicators provide probabilistic preliminary screening.'
        }

    # -------------------------------------------------------------
    # 1. METADATA & EXIF INSPECTION
    # -------------------------------------------------------------
    try:
        with Image.open(image_path) as pil_img:
            # Check info dictionary (PNG tEXt/iTXt, JPEG comments)
            info_str = " ".join([f"{k}:{v}" for k, v in pil_img.info.items() if isinstance(v, (str, bytes))]).lower()
            ai_keywords = [
                'stable diffusion', 'midjourney', 'dall-e', 'dalle', 'novelai',
                'comfyui', 'automatic1111', 'civitai', 'synthetic_demo', 'ai_generated'
            ]
            for kw in ai_keywords:
                if kw in info_str:
                    indicators.append(f"Metadata Tag: Generation signature identified in file metadata ('{kw}').")
                    metrics['metadata_ai_flag'] = True
                    break

            # Check EXIF software tag if available
            exif_data = pil_img.getexif()
            if exif_data:
                for tag_id, value in exif_data.items():
                    tag_name = ExifTags.TAGS.get(tag_id, str(tag_id))
                    val_str = str(value).lower()
                    for kw in ai_keywords:
                        if kw in val_str:
                            indicators.append(f"EXIF Software Tag: Generated by synthetic model ({val_str}).")
                            metrics['metadata_ai_flag'] = True
                            break
    except Exception:
        pass

    # -------------------------------------------------------------
    # 2. COMPUTER VISION: DIFFUSION NOISE IN FLAT REGIONS
    # Diffusion models leave subtle, uniform micro-noise across flat backgrounds
    # -------------------------------------------------------------
    cv_img = cv2.imread(image_path)
    if cv_img is not None:
        gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
        h, w = gray.shape

        # Select sample flat patches (typically corners away from borders)
        if h > 120 and w > 120:
            patch1 = gray[25:65, 25:65]
            patch2 = gray[h-65:h-25, w-65:w-25]
            patches = [p for p in [patch1, patch2] if p.size > 0]
            
            noise_scores = []
            for patch in patches:
                # Apply high-pass / Laplacian filter
                lap = cv2.Laplacian(patch, cv2.CV_64F)
                lap_std = float(np.std(lap))
                noise_scores.append(lap_std)

            if noise_scores:
                avg_noise = float(np.mean(noise_scores))
                metrics['diffusion_noise_score'] = round(avg_noise, 2)
                # In digital vector cards, flat patches have near zero noise (< 1.5).
                # Diffusion-generated synthetic cards exhibit persistent fine-grain micro-texture (8.0 - 28.0)
                # without physical print dot patterns.
                if 12.0 <= avg_noise <= 35.0:
                    indicators.append(
                        f"Frequency Analysis: High-frequency residual noise in flat card regions ({metrics['diffusion_noise_score']}), consistent with diffusion synthesis."
                    )

        # -------------------------------------------------------------
        # 3. TYPOGRAPHY & BASELINE ALIGNMENT CHECK
        # Real IDs have laser-straight, grid-aligned typography.
        # AI images show character baseline wobble and floating glyphs.
        # -------------------------------------------------------------
        try:
            # Threshold to isolate text blocks
            _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
            contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            char_boxes = []
            for cnt in contours:
                bx, by, bw, bh = cv2.boundingRect(cnt)
                # Filter typical character box sizes
                if 6 <= bw <= 45 and 10 <= bh <= 55 and bw * bh < 1800:
                    char_boxes.append((bx, by, bw, bh))

            if len(char_boxes) >= 15:
                # Group characters by rough horizontal line (similar y coordinates within 12px)
                char_boxes.sort(key=lambda b: (b[1] // 14, b[0]))
                lines = []
                current_line = []
                last_y = -100

                for b in char_boxes:
                    if abs(b[1] - last_y) < 12:
                        current_line.append(b)
                    else:
                        if len(current_line) >= 5:
                            lines.append(current_line)
                        current_line = [b]
                        last_y = b[1]
                if len(current_line) >= 5:
                    lines.append(current_line)

                # Check baseline variance across lines
                line_drifts = []
                for ln in lines:
                    bottoms = [b[1] + b[3] for b in ln]
                    drift = float(np.std(bottoms))
                    line_drifts.append(drift)

                if line_drifts:
                    avg_drift = float(np.mean(line_drifts))
                    metrics['baseline_drift_std'] = round(avg_drift, 2)
                    # Natural digital cards have baseline std < 1.2 px
                    # AI-hallucinated text has high baseline wobble (> 3.5 px)
                    if avg_drift > 3.8:
                        indicators.append(
                            f"Typography Inconsistency: Text baseline alignment drift detected (std {metrics['baseline_drift_std']}px), indicating AI-rendered text."
                        )
        except Exception:
            pass

        # -------------------------------------------------------------
        # 4. PHOTO & CARD INTEGRATION DISPARITY
        # Checks whether the photo box has unnatural edge bleeding or floating borders
        # -------------------------------------------------------------
        try:
            left_roi = cv_img[int(h * 0.15):int(h * 0.75), int(w * 0.05):int(w * 0.40)]
            if left_roi.size > 0:
                roi_gray = cv2.cvtColor(left_roi, cv2.COLOR_BGR2GRAY)
                edges = cv2.Canny(roi_gray, 50, 150)
                cnts, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                has_clean_rect_frame = False
                for c in cnts:
                    peri = cv2.arcLength(c, True)
                    approx = cv2.approxPolyDP(c, 0.04 * peri, True)
                    if len(approx) == 4:
                        px, py, pw, ph = cv2.boundingRect(approx)
                        aspect = float(pw) / float(ph)
                        if 0.65 <= aspect <= 0.95 and pw * ph > (left_roi.shape[0] * left_roi.shape[1] * 0.25):
                            has_clean_rect_frame = True
                            break

                roi_hsv = cv2.cvtColor(left_roi, cv2.COLOR_BGR2HSV)
                color_var = float(np.var(roi_hsv[:, :, 0]))
                if color_var > 800 and not has_clean_rect_frame:
                    metrics['photo_integration_anomaly'] = True
                    indicators.append(
                        "Visual Integration: Portrait element lacks defined security framing / displays irregular edge blending."
                    )
        except Exception:
            pass

    # -------------------------------------------------------------
    # 5. HALLUCINATORY & PSEUDO-TEXT PATTERNS (OCR Text Stream)
    # -------------------------------------------------------------
    if ocr_data:
        raw_text = ocr_data.get('raw_text', '')
        if raw_text:
            words = raw_text.split()
            hallucinatory_tokens = 0
            for w in words:
                if re.search(r'(.)\1{3,}', w):
                    hallucinatory_tokens += 1
                elif re.search(r'[bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]{6,}', w):
                    hallucinatory_tokens += 1

            metrics['hallucinatory_token_count'] = hallucinatory_tokens
            if hallucinatory_tokens >= 2:
                indicators.append(
                    f"Text Synthesis Artifacts: {hallucinatory_tokens} pseudo-word tokens / repetitive character motifs detected."
                )

    # -------------------------------------------------------------
    # CLASSIFY OVERALL AI / SYNTHETIC STATUS
    # -------------------------------------------------------------
    count = len(indicators)
    if count >= 2 or metrics['metadata_ai_flag']:
        status = 'FLAGGED'
        risk_penalty = 30
        details = f"Multiple synthetic/AI generation indicators identified ({count} flags): " + "; ".join(indicators)
    elif count == 1:
        status = 'WARNING'
        risk_penalty = 10
        details = f"Single synthetic anomaly observed: {indicators[0]}"
    else:
        status = 'PASSED'
        risk_penalty = 0
        details = "No significant synthetic or AI-generation indicators detected."

    return {
        'status': status,
        'indicator_count': count,
        'indicators': indicators,
        'risk_penalty': risk_penalty,
        'details': details,
        'metrics': metrics,
        'disclaimer': 'AI/Synthetic Indicators provide probabilistic preliminary screening and do not claim 100% forensic certainty.'
    }
